apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: k8s-troubleshooter
  namespace: kagent
spec:
  type: Declarative
  description: A simple Kubernetes troubleshooting agent using Ollama
  declarative:
    modelConfig: ollama-model-config
    systemMessage: |
      You are a Kubernetes troubleshooting assistant. Blahblahblah stuff here
  tools:
    - type: McpServer
      mcpServer:
        name: kagent-tool-server
        kind: RemoteMCPServer
        apiGroup: kagent.dev
        toolNames:
          - k8s_get_resources
    - type: McpServer
      mcpServer:
        name: kagent-tool-server
        kind: RemoteMCPServer
        apiGroup: kagent.dev
        toolNames:
          - k8s_describe_resource
    - type: McpServer
      mcpServer:
        name: kagent-tool-server
        kind: RemoteMCPServer
        apiGroup: kagent.dev
        toolNames:
          - k8s_get_pod_logs
    - type: McpServer
      mcpServer:
        name: kagent-tool-server
        kind: RemoteMCPServer
        apiGroup: kagent.dev
        toolNames:
          - k8s_get_events
